language: java
sudo: false # faster builds

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
